### ISSUE TITLE
Limit GPU memory used

### ISSUE THREAD

**Issue by armintoepfer** [mgawan/GPU-BSW#17]
Hi!

Is it possible to limit the GPU memory used? My goal is to use it in parallel with other GPU workers and I have to share resources.
I could provide the number of bytes that your API is allowed to allocate on the GPU.

Thanks,
Armin

**Comment by mgawan** [comment]
In commit e4ec58ceda725af05c32dc3a9e1b78d72ac0de07 I added an additional argument for kernel drivers, you can put an upper limit to GPU memory used by the kernels by providing a factor between 0 and 1.0 e.g. 0.5 would lead to an upper limit of 50% of total GPU memory.

**Comment by armintoepfer** [comment]
I personally would prefer the actual bytes in that API call and if someone wants to compute it via a factor, it should be done upstream. But I can also make those changes in my local checkout if you believe it doesn't make sense for your public API.

**Comment by mgawan** [comment]
I added the percentage with the idea that developers will not have to worry about the memory limits of the GPU since each GPU on the system might have different sized HBM. But it should be fairly simple to replace this with bytes if you want to take a stab at that. Otherwise I can do that on a separate branch and you can pull on that. Let me know.
